In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#importing the csv
df = pd.read_csv('adult.csv')
df.head()

39          State-gov   77516   Bachelors   13        Never-married  \
0  50   Self-emp-not-inc   83311   Bachelors   13   Married-civ-spouse   
1  38            Private  215646     HS-grad    9             Divorced   
2  53            Private  234721        11th    7   Married-civ-spouse   
3  28            Private  338409   Bachelors   13   Married-civ-spouse   
4  37            Private  284582     Masters   14   Married-civ-spouse   

         Adm-clerical   Not-in-family   White     Male   2174   0   40  \
0     Exec-managerial         Husband   White     Male      0   0   13   
1   Handlers-cleaners   Not-in-family   White     Male      0   0   40   
2   Handlers-cleaners         Husband   Black     Male      0   0   40   
3      Prof-specialty            Wife   Black   Female      0   0   40   
4     Exec-managerial            Wife   White   Female      0   0   40   

    United-States   <=50K  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3            Cuba   <=50K  
4   United-States   <=50K

In [3]:
df.shape

(32560, 15)

In [4]:
# Renaming the attributes
df = df.set_axis(['Age','Workclass','FNLWGT','Education','Edu_No.','Marital_Status','Occupation','Relationship','Race','Sex','Cptl_Gain','Cptl_Loss','Hours_p/w','Country','Income'],axis = 1)
df.head()

Age          Workclass  FNLWGT   Education  Edu_No.       Marital_Status  \
0   50   Self-emp-not-inc   83311   Bachelors       13   Married-civ-spouse   
1   38            Private  215646     HS-grad        9             Divorced   
2   53            Private  234721        11th        7   Married-civ-spouse   
3   28            Private  338409   Bachelors       13   Married-civ-spouse   
4   37            Private  284582     Masters       14   Married-civ-spouse   

           Occupation    Relationship    Race      Sex  Cptl_Gain  Cptl_Loss  \
0     Exec-managerial         Husband   White     Male          0          0   
1   Handlers-cleaners   Not-in-family   White     Male          0          0   
2   Handlers-cleaners         Husband   Black     Male          0          0   
3      Prof-specialty            Wife   Black   Female          0          0   
4     Exec-managerial            Wife   White   Female          0          0   

   Hours_p/w         Country  Income  
0         13   United-States   <=50K  
1         40   United-States   <=50K  
2         40   United-States   <=50K  
3         40            Cuba   <=50K  
4         40   United-States   <=50K

In [5]:
df.drop(['Marital_Status','Relationship','Race','Sex','Country'],axis=1,inplace=True)
df.head()

Age          Workclass  FNLWGT   Education  Edu_No.          Occupation  \
0   50   Self-emp-not-inc   83311   Bachelors       13     Exec-managerial   
1   38            Private  215646     HS-grad        9   Handlers-cleaners   
2   53            Private  234721        11th        7   Handlers-cleaners   
3   28            Private  338409   Bachelors       13      Prof-specialty   
4   37            Private  284582     Masters       14     Exec-managerial   

   Cptl_Gain  Cptl_Loss  Hours_p/w  Income  
0          0          0         13   <=50K  
1          0          0         40   <=50K  
2          0          0         40   <=50K  
3          0          0         40   <=50K  
4          0          0         40   <=50K

In [6]:
# Encoding the categorical values
from sklearn.preprocessing import LabelEncoder

le_workclass = LabelEncoder()
le_education = LabelEncoder()
le_occupation = LabelEncoder()
le_income = LabelEncoder()

df['Workclass_n'] = le_workclass.fit_transform(df['Workclass'])
df['Education_n'] = le_education.fit_transform(df['Education'])
df['Occupation_n'] = le_occupation.fit_transform(df['Occupation'])
df['Income_n'] = le_income.fit_transform(df['Income'])
df.drop(['Workclass','Education','Occupation','Income'], axis='columns',inplace=True)
df


Age  FNLWGT  Edu_No.  Cptl_Gain  Cptl_Loss  Hours_p/w  Workclass_n  \
0       50   83311       13          0          0         13            6   
1       38  215646        9          0          0         40            4   
2       53  234721        7          0          0         40            4   
3       28  338409       13          0          0         40            4   
4       37  284582       14          0          0         40            4   
...    ...     ...      ...        ...        ...        ...          ...   
32555   27  257302       12          0          0         38            4   
32556   40  154374        9          0          0         40            4   
32557   58  151910        9          0          0         40            4   
32558   22  201490        9          0          0         20            4   
32559   52  287927        9      15024          0         40            5   

       Education_n  Occupation_n  Income_n  
0                9             4         0  
1               11             6         0  
2                1             6         0  
3                9            10         0  
4               12             4         0  
...            ...           ...       ...  
32555            7            13         0  
32556           11             7         1  
32557           11             1         0  
32558           11             1         0  
32559           11             4         1  

[32560 rows x 10 columns]

In [7]:
x = df.iloc[:,:-1] #ind
y = df.iloc[:,-1]  #dep
print(type(x))
print(type(y))
print(x.shape)
print(y.shape)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
(32560, 9)
(32560,)


In [8]:
#splitting the dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(24420, 9)
(8140, 9)
(24420,)
(8140,)


In [9]:
# 1 --> Applying Decision Tree Model
from sklearn.tree import DecisionTreeClassifier

In [10]:
mod1 = DecisionTreeClassifier(criterion='gini')
mod1.fit(x_train,y_train)

DecisionTreeClassifier()

In [11]:
#Accuracy 
print("Training_Score",mod1.score(x_train,y_train))
print("Testing_Score",mod1.score(x_test,y_test))

Training_Score 0.9998771498771499
Testing_Score 0.772972972972973


In [12]:
# Computing the % of misclassification
mc_m1= 1 - mod1.score(x_test,y_test)
print('Misclassification Error = ',mc_m1* 100,'%')

Misclassification Error =  22.702702702702705 %


In [13]:
# Testing the Decision Tree
ypred_m1 = mod1.predict(x_test)
print(ypred_m1)

[1 1 0 ... 0 0 0]


In [14]:
# Computing Confusion Matrix & Classification Report
from sklearn.metrics import confusion_matrix, classification_report
c_m1 = confusion_matrix(y_test,ypred_m1)
print(c_m1)
print(classification_report(y_test,ypred_m1))

[[5238  985]
 [ 863 1054]]
              precision    recall  f1-score   support

           0       0.86      0.84      0.85      6223
           1       0.52      0.55      0.53      1917

    accuracy                           0.77      8140
   macro avg       0.69      0.70      0.69      8140
weighted avg       0.78      0.77      0.78      8140



In [15]:
# 2. --> Applying Random Forest Classifer
from sklearn.ensemble import RandomForestClassifier

mod2 = RandomForestClassifier(n_estimators=60,criterion='entropy')
mod2.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=60)

In [16]:
#Accuracy 
print("Training_Score",mod2.score(x_train,y_train))
print("Testing_Score",mod2.score(x_test,y_test))

Training_Score 0.9992628992628992
Testing_Score 0.8266584766584767


In [17]:
# Computing the % of misclassification
mc_m2 = 1 - mod2.score(x_test,y_test)
print('Misclassification Error = ',mc_m2* 100,'%')

Misclassification Error =  17.334152334152332 %


In [18]:
# Testing Random Forest
ypred_m2 = mod2.predict(x_test)
print(ypred_m2)

[1 1 0 ... 0 0 0]


In [19]:
# Computing Confusion Matrix & Classification Report
from sklearn.metrics import confusion_matrix, classification_report
c_m2 = confusion_matrix(y_test,ypred_m2)
print(c_m2)
print(classification_report(y_test,ypred_m2))

[[5733  490]
 [ 921  996]]
              precision    recall  f1-score   support

           0       0.86      0.92      0.89      6223
           1       0.67      0.52      0.59      1917

    accuracy                           0.83      8140
   macro avg       0.77      0.72      0.74      8140
weighted avg       0.82      0.83      0.82      8140



In [20]:
# 3. --> Applying KNN Classifer
from sklearn.neighbors import KNeighborsClassifier

mod3 = KNeighborsClassifier(n_neighbors=85)
mod3.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=85)

In [21]:
#Accuracy 
print("Training_Score",mod3.score(x_train,y_train))
print("Testing_Score",mod3.score(x_test,y_test))

Training_Score 0.7884930384930385
Testing_Score 0.7952088452088452


In [22]:
# Computing the % of misclassification
mc_m3 = 1 - mod3.score(x_test,y_test)
print('Misclassification Error = ',mc_m3 * 100,'%')

Misclassification Error =  20.479115479115485 %


In [23]:
# Testing the KNN
ypred_m3 = mod3.predict(x_test)
print(ypred_m3)

[0 0 0 ... 0 0 0]


In [24]:
# Computing Confusion Matrix & Classification Report
from sklearn.metrics import confusion_matrix, classification_report
c_m3 = confusion_matrix(y_test,ypred_m3)
print(c_m3)
print(classification_report(y_test,ypred_m3))

[[6215    8]
 [1659  258]]
              precision    recall  f1-score   support

           0       0.79      1.00      0.88      6223
           1       0.97      0.13      0.24      1917

    accuracy                           0.80      8140
   macro avg       0.88      0.57      0.56      8140
weighted avg       0.83      0.80      0.73      8140



In [25]:
# 4. --> Applying Naive Bayes
from sklearn.naive_bayes import GaussianNB

mod4 = GaussianNB()
mod4.fit(x_train,y_train) 

GaussianNB()

In [26]:
#Accuracy 
print("Training_Score",mod4.score(x_train,y_train))
print("Testing_Score",mod4.score(x_test,y_test))

Training_Score 0.7945945945945946
Testing_Score 0.7958230958230958


In [27]:
# Computing the % of misclassification
mc_m4 = 1 - mod4.score(x_test,y_test)
print('Misclassification Error = ',mc_m4 * 100,'%')

Misclassification Error =  20.417690417690416 %


In [28]:
# Testing Naive Bayes
ypred_m4 = mod4.predict(x_test)
print(ypred_m4)

[0 1 0 ... 0 0 0]


In [29]:
# Computing Confusion Matrix & Classification Report
from sklearn.metrics import confusion_matrix, classification_report
c_m4 = confusion_matrix(y_test,ypred_m4)
print(c_m4)
print(classification_report(y_test,ypred_m4))

[[5889  334]
 [1328  589]]
              precision    recall  f1-score   support

           0       0.82      0.95      0.88      6223
           1       0.64      0.31      0.41      1917

    accuracy                           0.80      8140
   macro avg       0.73      0.63      0.65      8140
weighted avg       0.77      0.80      0.77      8140



In [30]:
# 5. --> Applying Logistic Regression
from sklearn.linear_model import LogisticRegression

mod5 = LogisticRegression(solver="liblinear")
mod5.fit(x_train,y_train)


LogisticRegression(solver='liblinear')

In [31]:
#Accuracy 
print("Training_Score",mod5.score(x_train,y_train))
print("Testing_Score",mod5.score(x_test,y_test))

Training_Score 0.7971744471744472
Testing_Score 0.8006142506142506


In [32]:
# Computing the % of misclassification
mc_m5 = 1 - mod5.score(x_test,y_test)
print('Misclassification Error = ',mc_m5 * 100,'%')

Misclassification Error =  19.938574938574938 %


In [33]:
ypred_m5 = mod5.predict(x_test)
print(ypred_m4)

[0 1 0 ... 0 0 0]


In [34]:
# Computing Confusion Matrix & Classification Report
from sklearn.metrics import confusion_matrix, classification_report
c_m5 = confusion_matrix(y_test,ypred_m5)
print(c_m5)
print(classification_report(y_test,ypred_m5))

[[6008  215]
 [1408  509]]
              precision    recall  f1-score   support

           0       0.81      0.97      0.88      6223
           1       0.70      0.27      0.39      1917

    accuracy                           0.80      8140
   macro avg       0.76      0.62      0.63      8140
weighted avg       0.78      0.80      0.76      8140



In [35]:
result = min(mc_m1, mc_m2, mc_m3, mc_m4, mc_m5)
if result == mc_m1:
    print("Decision Tree has the best accuracy i.e. :", mod1.score(x_test, y_test) * 100, "%")
elif result == mc_m2:
    print("Random Forest has the best accuracy i.e. :", mod2.score(x_test, y_test) * 100, "%")
elif result == mc_m3:
    print("KNN has the best accuracy i.e. :", mod3.score(x_test, y_test) * 100, "%")
elif result == mc_m4:
    print("SVM has the best accuracy i.e. :", mod4.score(x_test, y_test) * 100, "%")
else:
    print("Logistic Regression has the best accuracy i.e. :", mod5.score(x_test, y_test) * 100, "%")

     
              

Random Forest has the best accuracy i.e. : 82.66584766584766 %
